### ISSUE TITLE
Unseen feature names at fit time

### ISSUE THREAD

**Issue by atmosphalanx** [Striker-Eurika/Group-1---IDS#2]
There is an issue with the saved model file. There appears to be a problem with the name of some features (columns). I've attached a screenshot of the error. It looks like something is wrong with how we process the feature names?
![Screenshot_2022-12-14_02-17-27](https://user-images.githubusercontent.com/73563195/207489341-8e09e780-7fd5-4030-8c4b-bb840911cc35.png)

**Comment by yhtprime** [comment]
Did you find some tips to slove this.

**Comment by atmosphalanx** [comment]
> Did you find some tips to slove this.

Yes. It ended up being a problem with data types.

**Comment by atmosphalanx** [comment]
Fixed data types.
